development:
  adapter: postgree
  timeout: 5000
  database: bird_catcher_dev

test:
  adapter: postgree
  timeout: 5000
  database: bird_catcher_hom

production:
  adapter: postgree
  timeout: 5000
  database: bird_catcher
