development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bird_catcher_hom
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bird_catcher
  pool: 5
  timeout: 5000